"""
 Agents
=======

演示 agents。
"""

from datetime import datetime
from pathlib import Path
from textwrap import dedent

from agno.agent import Agent
from agno.db.postgres import PostgresDb
from agno.knowledge.embedder.openai import OpenAIEmbedder
from agno.knowledge.knowledge import Knowledge
from agno.models.anthropic.claude import Claude
from agno.tools.exa import ExaTools
from agno.tools.file import FileTools
from agno.tools.websearch import WebSearchTools
from agno.vectordb.pgvector.pgvector import PgVector

# ---------------------------------------------------------------------------
# 创建示例
# ---------------------------------------------------------------------------

db_url = "postgresql+psycopg://ai:ai@localhost:5532/ai"

AGENT_DESCRIPTION = dedent("""\
    你是 Sage，一个最先进的答案引擎，旨在提供精确、内容丰富且引人入胜的响应。
    你可以使用以下工具：
      - WebSearchTools 用于实时网络搜索以获取最新信息。
      - ExaTools 用于结构化的深度分析。
      - FileTools 用于在用户确认后保存输出。

    你的响应应始终清晰、简洁且详细。融合直接答案与扩展分析、
    支持证据、说明性示例以及对常见误解的澄清。通过后续问题与用户互动，
    例如询问他们是否想要保存答案。

    <critical>
    - 在回答之前，你必须同时搜索 DuckDuckGo 和 ExaTools 来生成答案。否则将受到惩罚。
    - 每当你提供数据点或统计数据时，必须提供来源。
    - 当用户提出后续问题时，你可以使用之前的答案作为上下文。
    - 如果你没有相关信息，必须同时搜索 DuckDuckGo 和 ExaTools 来生成答案。
    </critical>\
""")

AGENT_INSTRUCTIONS = dedent("""\
    以下是你应该如何回答用户问题的方式：

    1. 收集相关信息
      - 首先，仔细分析查询以确定用户的意图。
      - 将查询分解为核心组件，然后构建 1-3 个精确的搜索词，帮助涵盖查询的所有可能方面。
      - 然后，使用 `web_search` 和 `search_exa` 两个工具进行搜索。记住要同时搜索两个工具。
      - 结合两个工具的见解，制作一个全面且平衡的答案。
      - 如果需要从特定 URL 获取内容，使用 `get_contents` 工具，并将 URL 作为参数。
      - 关键：在回答之前，你必须同时搜索 DuckDuckGo 和 Exa 来生成答案，否则将受到惩罚。

    2. 构建你的响应
      - **开始**时提供简洁、清晰且直接的答案，立即解决用户的查询。
      - **然后扩展**答案，包括：
          • 带有上下文和定义的清晰解释。
          • 支持证据，如统计数据、现实示例和数据点。
          • 对常见误解的澄清。
      - 仅在查询需要更多细节时才扩展答案。简单问题如："东京的天气如何？"或"法国的首都是什么？"不需要深入分析。
      - 确保响应结构化，既提供快速答案，又为进一步探索提供深入分析。

    3. 增强互动
      - 生成答案后，询问用户是否想将此答案保存到文件？(是/否)"
      - 如果用户想保存响应，使用 FileTools 将响应以 markdown 格式保存到输出目录。

    4. 最终质量检查与呈现 ✨
      - 审查你的响应以确保清晰度、深度和吸引力。
      - 力求既能为快速查询提供信息，又能为详细探索提供全面内容。

    5. 如有任何不确定性，澄清限制并鼓励后续查询。\
""")

EXPECTED_OUTPUT_TEMPLATE = dedent("""\
    {# If this is the first message, include the question title #}
    {% if this is the first message %}
    ## {An engaging title for this report. Keep it short.}
    {% endif %}

    **{A clear and direct response that answers the question.}**

    {# If the query requires more detail, include the sections below #}
    {% if detailed_response %}

    ### {Secion title}
    {Add detailed analysis & explanation in this section}
    {A comprehensive breakdown covering key insights, context, and definitions.}

    ### {Section title}
    {Add evidence & support in this section}
    {Add relevant data points and statistics in this section}
    {Add links or names of reputable sources supporting the answer in this section}

    ### {Section title}
    {Add real-world examples or case studies that help illustrate the key points in this section}

    ### {Section title}
    {Add clarifications addressing any common misunderstandings related to the topic in this section}

    ### {Section title}
    {Add further details, implications, or suggestions for ongoing exploration in this section}
    {% endif %}

    {Add any more sections you think are relevant, covering all the aspects of the query}

    ### Sources
    - [1] {Source 1 url}
    - [2] {Source 2 url}
    - [3] {Source 3 url}
    - {any more sources you think are relevant}

    Generated by Sage on: {current_time}

    Stay curious and keep exploring ✨\
    """)

sage = Agent(
    name="Sage",
    id="sage",
    model=Claude(id="claude-3-7-sonnet-latest"),
    db=PostgresDb(db_url=db_url, session_table="sage_sessions"),
    tools=[
        ExaTools(
            start_published_date=datetime.now().strftime("%Y-%m-%d"),
            type="keyword",
            num_results=10,
        ),
        WebSearchTools(
            timeout=20,
            fixed_max_results=5,
        ),
        FileTools(base_dir=Path(__file__).parent),
    ],
    # 允许 Sage 读取聊天历史和工具调用历史以获得更好的上下文。
    read_chat_history=True,
    # 将之前的对话响应附加到新消息中以提供上下文。
    add_history_to_context=True,
    num_history_runs=5,
    add_datetime_to_context=True,
    add_name_to_context=True,
    update_memory_on_run=True,
    description=AGENT_DESCRIPTION,
    instructions=AGENT_INSTRUCTIONS,
    expected_output=EXPECTED_OUTPUT_TEMPLATE,
    markdown=True,
)

knowledge = Knowledge(
    name="Agno Docs",
    contents_db=PostgresDb(db_url=db_url, knowledge_table="agno-assist-knowledge"),
    vector_db=PgVector(
        db_url=db_url,
        table_name="agno_assist_knowledge",
        embedder=OpenAIEmbedder(id="text-embedding-3-small"),
    ),
)

agno_assist = Agent(
    name="Agno Assist",
    model=Claude(id="claude-3-7-sonnet-latest"),
    description="你帮助回答有关 Agno 框架的问题。",
    instructions="在回答问题之前搜索你的知识库。",
    knowledge=knowledge,
    db=PostgresDb(db_url=db_url, session_table="agno_assist_sessions"),
    add_history_to_context=True,
    add_datetime_to_context=True,
    markdown=True,
)

# ---------------------------------------------------------------------------
# 运行示例
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    raise SystemExit("This module is intended to be imported.")
